Repository wp-cli/entity-command, pull requests merged in 2018-04, with the labels that each got.

#163 Raise memory limit to 2048MB
  .travis.yml
Labels: scope:testing

#168 Improve the formatting of various format parameter documentation
  README.md
  src/User_Meta_Command.php
  src/WP_CLI/CommandWithMeta.php
  src/WP_CLI/CommandWithTerms.php
Labels: scope:documentation

#171 Turn `latest` into actual version number
  bin/test.sh
Labels: bug, scope:testing

#177 Fix tests after Core's introduction of a default "Privacy Policy" page
  features/post.feature
  features/site-empty.feature
Labels: scope:testing

#173 Remove duplicative `--user_email=<user-email>` argument
  README.md
  src/User_Command.php
Labels: bug, command:user-create, scope:documentation
