Repository wp-cli/entity-command, pull requests merged in 2018-08, with the labels that each got.

#192 Adapt package for framework v2
  .travis.yml
  bin/install-package-tests.sh
  bin/test.sh
  composer.json
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/ProcessRun.php
  features/bootstrap/support.php
  features/bootstrap/utils.php
  features/extra/no-mail.php
  features/steps/given.php
  features/steps/then.php
  features/steps/when.php
  features/user-import-csv.feature
  src/Option_Command.php
  src/Site_Option_Command.php
  src/WP_CLI/CommandWithMeta.php
  src/WP_CLI/Entity/Utils.php
  utils/behat-tags.php
Labels: scope:distribution

#193 Add `behat.yml` file for Windows compatibility
  behat.yml
Labels: scope:distribution

#200 Automatically rerun failed scenarios
  .travis.yml
  composer.json
Labels: scope:testing

#204 Update readme
  README.md
  src/Post_Command.php
Labels: scope:documentation
