Repository wp-cli/entity-command, pull requests merged in 2018-02, with the labels that each got.

#146 Fix category list count
  src/Site_Command.php
Labels: bug, command:site-empty, good-first-issue

#147 Fix missing quote in documentation
  README.md
  src/Post_Command.php
Labels: bug, scope:documentation

#148 Update license copyright date to 2018
  LICENSE
Labels: scope:documentation
