Repository wp-cli/entity-command, pull requests merged in 2018-10, with the labels that each got.

#212 Use "installation" instead of "install"
  entity-command.php
  features/network-meta.feature
  src/User_Command.php
Labels: scope:testing

#217 Fix - #216 user description was not getting saved
  features/user-meta.feature
  src/User_Command.php
Labels: bug, command:user-create

#213 Improve documentation
  src/Comment_Command.php
  src/Post_Command.php
Labels: scope:documentation

#219 Add support for Probot `move` command
  .github/move.yml
Labels: scope:distribution
