Repository wp-cli/entity-command, pull requests merged in 2020-04, with the labels that each got.

#286 Fix Travis CI `sudo` warning
  .travis.yml
Labels: scope:distribution

#284 Update `site empty` command to include removal of `wp_links` table data
  features/site-empty.feature
  src/Site_Command.php
Labels: command:site-empty

#288 Bump Travis CI OS from `trusty` to `xenial`
  .travis.yml
  composer.json
Labels: scope:testing

#287 Enforce PHP 7.4 compatibility in Travis CI
  .travis.yml
Labels: scope:testing
