Repository wp-cli/entity-command, pull requests merged in 2021-12, with the labels that each got.

#331 Support PHP 8.1
  composer.json
  src/User_Command.php
Labels: scope:distribution

#321 Clarified behavior in favor of a fix for #298
  src/Post_Command.php
Labels: scope:documentation

#312 Correct the home URL when listing sites
  src/Site_Command.php
Labels: command:site-list

#326 Update example input to reflect example output
  src/Post_Command.php
Labels: scope:documentation

#304 Better error message when trying to delete super admin
  composer.json
  features/user.feature
  src/Site_Command.php
  src/User_Command.php
Labels: command:user-delete

#339 Adapt http => https URLs
  features/comment.feature
  features/menu-item.feature
  features/option.feature
  features/post.feature
  features/site-empty.feature
  features/site.feature
  features/term.feature
  features/user.feature
Labels: scope:testing
