Repository wp-cli/entity-command, pull requests merged in 2024-02, with the labels that each got.

#438 Add filter site__user_in on wp site list
  README.md
  features/site.feature
  src/Site_Command.php
Labels: command:site, command:site-list

#466 Update term commands examples
  src/Term_Command.php
Labels: scope:documentation

#465 Update example out put of `comment delete` command
  src/Comment_Command.php
Labels: scope:documentation

#467 Update examples in user commands
  src/User_Command.php
Labels: scope:documentation

#468 Fix example for site deactivate command
  src/Site_Command.php
Labels: scope:documentation

#462 Fix menu command output examples
  src/Menu_Command.php
  src/Menu_Item_Command.php
  src/Menu_Location_Command.php
Labels: scope:documentation

#470 Fix dynamic property issue in user session class
  src/User_Session_Command.php
Labels: bug, command:user-session

#469 Fix PHP notice in comment recount with invalid ID
  features/comment-recount.feature
  src/Comment_Command.php
Labels: bug, command:comment-recount
